import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      businessName,
      contactName,
      email,
      phone,
      address,
      serviceType,
      experience,
      description,
      availability
    } = body;

    // Validate required fields
    if (!businessName || !contactName || !email || !phone || !address || !serviceType || !experience || !description || !availability) {
      return NextResponse.json(
        { error: 'All fields are required' },
        { status: 400 }
      );
    }

    // Create transporter (using Gmail as an example - you can configure this based on your email provider)
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST || 'smtp.hostinger.com',
        port: 587,
      auth: {
        user: process.env.EMAIL_USER, // Your email
        pass: process.env.EMAIL_PASS, // Your app password
      },
    });

    // Email content for the admin
    const adminEmailHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
          New Vendor Application - SeniorSync
        </h2>
        
        <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1f2937; margin-top: 0;">Business Information</h3>
          <p><strong>Business Name:</strong> ${businessName}</p>
          <p><strong>Service Type:</strong> ${serviceType}</p>
          <p><strong>Business Address:</strong> ${address}</p>
        </div>

        <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1f2937; margin-top: 0;">Contact Information</h3>
          <p><strong>Contact Name:</strong> ${contactName}</p>
          <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
          <p><strong>Phone:</strong> <a href="tel:${phone}">${phone}</a></p>
        </div>

        <div style="background-color: #f0fdf4; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1f2937; margin-top: 0;">Service Details</h3>
          <p><strong>Years of Experience:</strong> ${experience}</p>
          <p><strong>Service Description:</strong></p>
          <p style="background-color: white; padding: 15px; border-radius: 4px; border-left: 4px solid #10b981;">
            ${description}
          </p>
          <p><strong>Availability:</strong></p>
          <p style="background-color: white; padding: 15px; border-radius: 4px; border-left: 4px solid #10b981;">
            ${availability}
          </p>
        </div>

        <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; font-size: 14px; color: #92400e;">
            <strong>Next Steps:</strong> Please review this application and contact the vendor if additional information is needed.
          </p>
        </div>

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">
        <p style="font-size: 12px; color: #6b7280; text-align: center;">
          This email was automatically generated by SeniorSync vendor application system.
        </p>
      </div>
    `;

    // Email content for the vendor (confirmation)
    const vendorEmailHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
          Application Received - SeniorSync
        </h2>
        
        <p>Dear ${contactName},</p>
        
        <p>Thank you for your interest in joining the SeniorSync vendor network! We have successfully received your application for <strong>${businessName}</strong>.</p>

        <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1f2937; margin-top: 0;">What happens next?</h3>
          <ul style="color: #374151;">
            <li>Our team will review your application within 1-2 business days</li>
            <li>We may contact you for additional information or clarification</li>
            <li>Upon approval, you'll receive onboarding instructions via email</li>
            <li>You'll get access to your vendor dashboard to manage requests</li>
          </ul>
        </div>

        <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #1f2937; margin-top: 0;">Application Summary</h3>
          <p><strong>Business:</strong> ${businessName}</p>
          <p><strong>Service Type:</strong> ${serviceType}</p>
          <p><strong>Contact Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone}</p>
        </div>

        <p>If you have any questions about your application, please don't hesitate to contact us at <a href="mailto:feiyue@seniorsync.fun">feiyue@seniorsync.fun</a>.</p>

        <p>Best regards,<br>
        <strong>The SeniorSync Team</strong></p>

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">
        <p style="font-size: 12px; color: #6b7280; text-align: center;">
          SeniorSync - Connecting seniors with trusted care service providers<br>
          This is an automated confirmation email.
        </p>
      </div>
    `;

    // Send email to admin
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: process.env.RECIPIENT_EMAIL,
      subject: `New Vendor Application: ${businessName} - ${serviceType}`,
      html: adminEmailHTML,
    });

    // Send confirmation email to vendor
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email,
      subject: 'Application Received - SeniorSync Vendor Network',
      html: vendorEmailHTML,
    });

    return NextResponse.json(
      { 
        message: 'Application submitted successfully and emails sent',
        success: true 
      },
      { status: 200 }
    );

  } catch (error) {
    console.error('Error sending vendor application email:', error);
    return NextResponse.json(
      { 
        error: 'Failed to process application. Please try again later.',
        success: false 
      },
      { status: 500 }
    );
  }
}
