CREATE TABLE senior_sync.fsm_transitions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_name VARCHAR,
  trigger      VARCHAR,
  source_state VARCHAR,
  dest_state   VARCHAR,
  guard_name   VARCHAR,
  action_name  VARCHAR,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_trigger_source_dest_state UNIQUE(trigger, source_state, dest_state)
);

CREATE TRIGGER fsm_transitions_updated_at
  BEFORE UPDATE ON senior_sync.fsm_transitions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();