CREATE TABLE senior_sync.seniors (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name       VARCHAR      NOT NULL,
  last_name        VARCHAR      NOT NULL,
  date_of_birth    DATE,
  contact_phone    VARCHAR(20),
  contact_email    VARCHAR(255),
  address          VARCHAR,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- NOTE: This table is not finalised and is pending the spae of SGO's data

CREATE TRIGGER seniors_updated_at
  BEFORE UPDATE ON senior_sync.seniors
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();