CREATE TABLE senior_sync.care_level_types (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_level      VARCHAR(50)  NOT NULL UNIQUE,
    care_level_color VARCHAR(50)
);

-- Insert common request types for senior assistance
INSERT INTO senior_sync.care_level_types (care_level, care_level_color)
VALUES
    ('LOW', '#28a745'),
    ('MEDIUM', '#ffc107'),
    ('HIGH', '#fd7e14'),
    ('CRITICAL', '#dc3545'),
    ('INDEPENDENT', '#17a2b8'),
    ('SUPERVISED', '#6f42c1');