-- 1. Create the centers table to store tenant information
CREATE TABLE senior_sync.centers (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL UNIQUE,
  address     VARCHAR,
  contact_phone VARCHAR(20),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TRIGGER centers_updated_at
  BEFORE UPDATE ON senior_sync.centers
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- 2. Add center_id to all tenant-specific tables
ALTER TABLE senior_sync.staff ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
ALTER TABLE senior_sync.seniors ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
ALTER TABLE senior_sync.senior_requests ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
-- ALTER TABLE senior_sync.request_comments ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
-- ALTER TABLE senior_sync.reminders ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
-- ALTER TABLE senior_sync.conversations ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);
-- ALTER TABLE senior_sync.senior_request_drafts ADD COLUMN center_id BIGINT REFERENCES senior_sync.centers(id);

-- 3. Add indexes for performance
CREATE INDEX idx_staff_center_id ON senior_sync.staff(center_id);
CREATE INDEX idx_seniors_center_id ON senior_sync.seniors(center_id);
CREATE INDEX idx_senior_requests_center_id ON senior_sync.senior_requests(center_id);

--Create a default center and assign all existing records to it.
INSERT INTO senior_sync.centers (name) VALUES ('Test Center');
UPDATE senior_sync.staff SET center_id = 1 WHERE center_id IS NULL;
UPDATE senior_sync.seniors SET center_id = 1 WHERE center_id IS NULL;
UPDATE senior_sync.senior_requests SET center_id = 1 WHERE center_id IS NULL;
-- UPDATE senior_sync.request_comments SET center_id = 1 WHERE center_id IS NULL;
-- UPDATE senior_sync.reminders SET center_id = 1 WHERE center_id IS NULL;
-- UPDATE senior_sync.conversations SET center_id = 1 WHERE center_id IS NULL;
-- UPDATE senior_sync.senior_request_drafts SET center_id = 1 WHERE center_id IS NULL;