CREATE TABLE senior_sync.requests_ranking (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES senior_sync.senior_requests(id) ON DELETE CASCADE,
    priority_score INT NOT NULL CHECK (priority_score >= 1 AND priority_score <= 100),
    ranking_factors JSONB,
    UNIQUE(request_id)
);

CREATE INDEX idx_requests_ranking_priority_score ON senior_sync.requests_ranking(priority_score DESC);
CREATE INDEX idx_requests_ranking_request_id ON senior_sync.requests_ranking(request_id);

