CREATE TABLE senior_sync.care_level_types (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_level      VARCHAR(50)  NOT NULL UNIQUE,
    care_level_color VARCHAR(50),
    center_id       BIGINT       REFERENCES senior_sync.centers(id)
);

-- Insert common request types for senior assistance
INSERT INTO senior_sync.care_level_types (care_level, care_level_color, center_id)
VALUES
    ('LOW', '#28a745', 1),
    ('MEDIUM', '#ffc107', 1),
    ('HIGH', '#fd7e14', 1),
    ('CRITICAL', '#dc3545', 1),
    ('INDEPENDENT', '#17a2b8', 1),
    ('SUPERVISED', '#6f42c1', 1);



