CREATE TABLE senior_sync.senior_request_drafts (
  id                BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  senior_id         BIGINT         REFERENCES senior_sync.seniors(id) ON DELETE CASCADE,
  assigned_staff_id BIGINT         REFERENCES senior_sync.staff(id) ON DELETE SET NULL,
  request_type_id   BIGINT         REFERENCES senior_sync.request_types(id),
  title             VARCHAR,
  description       VARCHAR,
  priority          SMALLINT       DEFAULT 1,
  created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ    NOT NULL DEFAULT now()
);
-- no status and completed_at columns