CREATE TABLE senior_sync.fsm_state_reply_option (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_name VARCHAR,
  state      VARCHAR NOT NULL,
  content    VARCHAR NOT NULL,
  event      VARCHAR NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_state_content_event UNIQUE(state, content, event)
);

CREATE TRIGGER fsm_state_reply_option_updated_at
  BEFORE UPDATE ON senior_sync.fsm_state_reply_option
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();