CREATE TABLE senior_sync.conversations (
  id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  senior_id      BIGINT         NOT NULL,
  campaign_name  VARCHAR(100)   NOT NULL,
  current_state  VARCHAR(100)   NOT NULL,
  extended_state JSONB          NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE senior_sync.messages (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  BIGINT       NOT NULL REFERENCES senior_sync.conversations(id),
  direction        VARCHAR(10)  NOT NULL, -- 'IN' or 'OUT'
  content          TEXT         NOT NULL,
  event            VARCHAR(100),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TRIGGER conversations_updated_at
  BEFORE UPDATE ON senior_sync.conversations
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER messages_updated_at
  BEFORE UPDATE ON senior_sync.messages
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();