CREATE TABLE senior_sync.staff (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name       VARCHAR      NOT NULL,
  last_name        VARCHAR      NOT NULL,
  role             VARCHAR(255) NOT NULL,
  contact_phone    VARCHAR(20),
  contact_email    VARCHAR(255),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TRIGGER staff_updated_at
  BEFORE UPDATE ON senior_sync.staff
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();