name: Frontend CI

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - "crm-ui/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  frontend-ci:
    name: Frontend Type Check and Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crm-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: crm-ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run type-check

      # Skip for now
      # - name: Run linting
      #   run: npm run lint

      # Commenting out tests until test suite is implemented
      # - name: Run tests
      #   run: npm test -- --coverage --watchAll=false
      #   env:
      #     CI: true

      - name: Build application
        run: npm run build
  
  frontend-synk-scan:
    runs-on: ubuntu-latest
    needs: [frontend-ci]
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # Status check for PR protection
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [frontend-ci]
    if: always()

    steps:
      - name: Check CI status
        run: |
          if [[ "${{ needs.frontend-ci.result }}" == "failure" ]]; then
            echo "❌ Frontend CI checks failed"
            exit 1
          fi
          echo "✅ CI checks completed"
